### ISSUE TITLE
[Broken Plugin?] RestartButton

### ISSUE THREAD

**Issue by Random-Access-Exomemory** [zt64/aliucord-plugins#1]
Heya, just creating an issue to let you know that RestartButton is broken haha, here's screenshots
![Screenshot_2021-09-03-19-31-07-209_com aliucord](https://user-images.githubusercontent.com/88039945/132051387-990b99db-2548-4850-ac7b-6f72b68982d4.jpg)
![Screenshot_2021-09-03-19-31-24-426_com aliucord](https://user-images.githubusercontent.com/88039945/132051392-8b031d04-7d87-45d4-b6d6-21c2abe41d0e.jpg)

**Comment by zt64** [comment]
It's a known issue, I'm not sure of a fix and it only effects some users. I would fix it if I knew what was wrong

**Comment by Random-Access-Exomemory** [comment]
Ah okay then, thanks anyway haha

**Comment by Random-Access-Exomemory** [comment]
Uh, today the RestartButton plugin just started working for me @zt64 lol

**Comment by Random-Access-Exomemory** [comment]
It was after the latest Aliucord update
