### ISSUE TITLE
[CharCounter] Customisable threshold for counter to appear

### ISSUE THREAD

**Issue by pointydev** [zt64/aliucord-plugins#17]
On desktop, the native character limit only appears once you have a certain amount of characters remaining in your message.

It'd be nice to be able to customise when the plugin shows the counter to somewhat replicate this behaviour.

Thanks,
pointy

**Comment by zt64** [comment]
Added in V1.4.0 (f15ec9f93530148c399d1a21132b03dd1909e086)
