### ISSUE TITLE
[CharCounter] Reverse counter

### ISSUE THREAD

**Issue by pointydev** [zt64/aliucord-plugins#18]
This relates to the desktop behaviour described in #17, where instead of the counter displaying an absolute value, it would display a relative negative count until the limit is reached.

I think this would fit well if #17 was to be implemented, as they compliment each other.

Thanks,
pointy

**Comment by zt64** [comment]
Added in V1.4.0 (f15ec9f93530148c399d1a21132b03dd1909e086)
