### ISSUE TITLE
Random Emote

### ISSUE THREAD

**Issue by vy-storm** [zt64/aliucord-plugins#2]
Random emote doesn't work for me, it just crashes.  But also, does it pull from every emote or just default ones?

**Comment by vy-storm** [comment]
I got into a bootloop of sorts with aliucord and the resulting reinstall fixed the crashing, so there was probably something messed up on my client for that.

But I have noticed it only sends default emotes, is there any easy way to make it send from all emotes?

**Comment by zt64** [comment]
> I got into a bootloop of sorts with aliucord and the resulting reinstall fixed the crashing, so there was probably something messed up on my client for that.
> 
> But I have noticed it only sends default emotes, is there any easy way to make it send from all emotes?

I thought about adding the ability to send a random emote from the current guild but it seemed like it'll be a little more difficult and it wasn't specified in the request so I left it out for now
