### ISSUE TITLE
DM Categories

### ISSUE THREAD

**Issue by lolpowerluke** [zt64/aliucord-plugins#25]
Can you add a setting to remove the lines underneath the categories?
Also, if possible, another setting to leave the line for the last category

**Comment by lolpowerluke** [comment]
And another thing, if possible, could you add a way to edit the category order

**Comment by zt64** [comment]
I'll work on the line stuff tomorrow. Editing category order though will have to wait since I'm unsure how to do that currently

**Comment by zt64** [comment]
Added
