### ISSUE TITLE
RoleColorEverywhere - Voice Channels

### ISSUE THREAD

**Issue by Zefferis** [zt64/aliucord-plugins#3]
![Screenshot_20210905-143942.jpg](https://user-images.githubusercontent.com/15270437/132142135-89f5b54f-6613-48c3-8b7a-99d689fdf27f.jpg)

Issue:
It seems people are inheriting the color of roles above them?

Where:
Voice Channels - Users List 

Users: 
Karii, Lax, Ristar do not have colored roles.

**Comment by zt64** [comment]
> ![Screenshot_20210905-143942.jpg](https://user-images.githubusercontent.com/15270437/132142135-89f5b54f-6613-48c3-8b7a-99d689fdf27f.jpg)
> 
> Issue:
> It seems people are inheriting the color of roles above them?
> 
> Where:
> Voice Channels - Users List
> 
> Users:
> Karii, Lax, Ristar do not have colored roles.

Is this issue still happening? I'm unable to reproduce it
