### ISSUE TITLE
[TextReact] Add Emotes

### ISSUE THREAD

**Issue by vy-storm** [zt64/aliucord-plugins#40]
Add the ability to quickly mark emotes in your collection as characters.

To further this, having two separate options would be ideal. One for adding entire alphabets (in the cases where a server has its own full lettering emote pack) and another for adding single characters (in the case where an emote you have is a suitable substitute for a given letter.

Settings could then also be added to weight which characters are used, including a way to rank alphabets and characters in order of priority, where the highest ranked available alphabet or single character is used first. A toggle to choose suitable characters at random from all that have been added may also be nice for some although I would not personally use it.

**Comment by zt64** [comment]
I didn't make TextReact though
