### ISSUE TITLE
Account Switcher

### ISSUE THREAD

**Issue by Strongfox** [zt64/aliucord-plugins#44]
When I use add current account the account loads and then when I press the button in the top right of the screen and then press back then go back to user settings and then back to settings of account switcher it disappears. I have also tried inputing my token and the option to confirm is grayed out. It's 70 characters long but if I shorten it to 59 charaters the confirm button appears blue and clickable. I have also tried switching accounts and adding it on the other account and no luck. I have also tried my token in the login by token option in the login screen of the app and the token works. I have also used /token to grab my token and also use add current account and click the edit button and grab it that way and it all works to log in with token but not to add to account switcher.

**Comment by thepistoneer** [comment]
I have the same issue here, I think it's because the token length has been changed to 70 characters but the plugin hasn't updated and so only accepts old tokens which are 59 characters.

**Comment by zt64** [comment]
Should now be fixed with 7430188
