### ISSUE TITLE
AccountSwitcher not support new token format

### ISSUE THREAD

**Issue by pp0236** [zt64/aliucord-plugins#50]
video ¿
https://media.discordapp.net/attachments/721713679216672838/1001316518010835004/Screen_Recording_20220726-092233.mp4

proof token was vaild
![Screenshot_20220726-092934_Termux](https://user-images.githubusercontent.com/54238880/180910745-502fb54a-f4f5-472f-bfcc-4bc31dab8c15.jpg)

latest version
![Screenshot_20220726-092245](https://user-images.githubusercontent.com/54238880/180910649-4d6cc365-2e14-43ac-91c3-21a4dffd5954.jpg)

**Comment by zt64** [comment]
Interesting, I'll have to figure out the pattern they're using for tokens

**Comment by Bluscream** [comment]
Cant you just atleast temporarily make it not do any checks before the "Confirm" button becomes enables?
Or atleast throw to the login page of the "account" instance instead of just making the "token invalid" toast?

It is really annoying having to edit the json file on my phone every few days

**Comment by zt64** [comment]
Fixed in 7430188
