### ISSUE TITLE
Mosaic plugin is broken

### ISSUE THREAD

**Issue by lynxnb** [zt64/aliucord-plugins#75]
The Mosaic plugin crashes the Aliucord client because of `unhandled view type 500` exception. I've seen the Mosaic plugin code is mostly commented out, is there any reason for it?

The plugin is also still on the plugin repo in this very broken state, it would be best to remove it if development has ceased.

**Comment by Happ1ness-dev** [comment]
Can confirm, it crashes for me on latest Aliucord version (ADF80A8) with the same error.
I'm on Poco F3, running on Android 12 (MIUI 13.0.7)

**Comment by zt64** [comment]
Mosaic plugin isn't released
