### ISSUE TITLE
Favourite Channel doesn't include threads 

### ISSUE THREAD

**Issue by PeterKW** [zt64/aliucord-plugins#89]
https://github.com/zt64/aliucord-plugins/commit/9ffae96b6b4d5a3afdbe26f36fa03ef710d8b91a

Thank you very much for the plugin. It is very useful. 

When moving a channel it moves to the top as expected. If that channel has active threads the threads stay inplace and don't move with the channel they are from

**Comment by zt64** [comment]
Good catch, I'll see if I can figure out how to fix it

**Comment by zt64** [comment]
Pretty simple fix, ded34b8701ea3471cf5ed07f7cd142bfbda2d810.
