### ISSUE TITLE
Difficulty turning off DisablePreviewsOnData 

### ISSUE THREAD

**Issue by PeterKW** [zt64/aliucord-plugins#92]
https://github.com/zt64/aliucord-plugins/raw/builds/DisablePreviewsOnData.zip

I have this plugin disabled but the previews are still not appearing of photographs? 

I have tried restarting aliucord. 

I will attempt to attach some screenshots

**Comment by zt64** [comment]
Did you re-enable these options? 
![Screenshot_20240921_015458](https://github.com/user-attachments/assets/48ed074e-b0ac-4a25-8fa3-854f957a53ff)

**Comment by PeterKW** [comment]
Thank you for the response.

Attached are my settings for that page. Anything else I could try? 

# Is there a way to toggle disable all plugins?

![Screenshot_20240921-114203.png](https://github.com/user-attachments/assets/6776c371-a2c5-467e-b59b-2f5508fcc901)

**Comment by zt64** [comment]
I don't think this is an issue with plugins based on this screenshot. The images might just be a in a format which isn't displayable in app or something else but DisablePreviewsOnData wouldn't do that
